# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchDemo', '0003_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
