# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchDemo', '0006_auto_20180128_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, default=b'', max_length=255),
        ),
    ]
